/* Configuration for p2_cpc_2025 generated by Alire */
#ifndef P2_CPC_2025_CONFIG_H
#define P2_CPC_2025_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "p2_cpc_2025"

#define ALIRE_HOST_OS "windows"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "distribution_unknown"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
